<?php

namespace Database\Seeders;

use App\Models\Township;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TownshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $objs = array(
            ['city_id' => '4', 'name' => 'Myitkyina', 'name_mm' => 'မြစ်ကြီးနား', 'id' => '1'],
            ['city_id' => '4', 'name' => 'Bhamo (Bamaw)', 'name_mm' => 'ဘားမော်', 'id' => '2'],
            ['city_id' => '4', 'name' => 'Bharma', 'name_mm' => 'ဗန်းမာ', 'id' => '3'],
            ['city_id' => '4', 'name' => 'Chipwi (Chibwe)', 'name_mm' => 'ချီပွီ', 'id' => '4'],
            ['city_id' => '4', 'name' => 'Hpakant (Hpakan, Farkent)', 'name_mm' => 'ဖားကန့်', 'id' => '5'],
            ['city_id' => '4', 'name' => 'Hopin (Hobik)', 'name_mm' => 'ဟိုပင်', 'id' => '6'],
            ['city_id' => '4', 'name' => 'Hsinbo (Sinbo)', 'name_mm' => 'ဆင်ဖို', 'id' => '7'],
            ['city_id' => '4', 'name' => 'Hsawlaw (Sawlaw)', 'name_mm' => 'ဆော့လော', 'id' => '8'],
            ['city_id' => '4', 'name' => 'Injangyang', 'name_mm' => 'အင်ဂျင်းယန်', 'id' => '9'],
            ['city_id' => '4', 'name' => 'Kamaing (Kamine)', 'name_mm' => 'ကမ်းအင်', 'id' => '10'],
            ['city_id' => '4', 'name' => 'Kawnglanghpu (Kaunglanfu)', 'name_mm' => 'ကောင်းလောင်ဖူ', 'id' => '11'],
            ['city_id' => '4', 'name' => 'Lweje (Loije, Lwalgyai)', 'name_mm' => 'လွှယ်ယည်', 'id' => '12'],
            ['city_id' => '4', 'name' => 'Machanbaw', 'name_mm' => 'မချန်ဘော', 'id' => '13'],
            ['city_id' => '4', 'name' => 'Mansi', 'name_mm' => 'မဏစ်', 'id' => '14'],
            ['city_id' => '4', 'name' => 'Momauk', 'name_mm' => 'မိုမောက်', 'id' => '15'],
            ['city_id' => '4', 'name' => 'Moekaung', 'name_mm' => 'မိုက်ကောင်', 'id' => '16'],
            ['city_id' => '4', 'name' => 'Mohnyin', 'name_mm' => 'မိုးညှင်', 'id' => '17'],
            ['city_id' => '4', 'name' => 'Nogmung (Naungmoon)', 'name_mm' => 'နောင်မွန်', 'id' => '18'],
            ['city_id' => '4', 'name' => 'Pannandin', 'name_mm' => 'ပန်းနန်း', 'id' => '19'],
            ['city_id' => '4', 'name' => 'Putao', 'name_mm' => 'ပူတာအို', 'id' => '20'],
            ['city_id' => '4', 'name' => 'Shwegu', 'name_mm' => 'ရွှေဂူး', 'id' => '21'],
            ['city_id' => '4', 'name' => 'Sumprabum', 'name_mm' => 'ဆွမ်ပရာဘွမ်', 'id' => '22'],
            ['city_id' => '4', 'name' => 'Tanai (Tanain)', 'name_mm' => 'တနိုင်', 'id' => '23'],
            ['city_id' => '4', 'name' => 'Tsawlaw (Sawlaw)', 'name_mm' => 'ဆော့လော', 'id' => '24'],
            ['city_id' => '4', 'name' => 'Waingmaw', 'name_mm' => 'ဝိုင်းမော်', 'id' => '25'],
            ['city_id' => '4', 'name' => 'Ywathit', 'name_mm' => 'ရွာသစ်', 'id' => '26'],
            ['city_id' => '5', 'name' => 'Loikaw', 'name_mm' => 'လွိုင်ကော်', 'id' => '27'],
            ['city_id' => '5', 'name' => 'Demawso', 'name_mm' => 'ဒီမော့ဆို', 'id' => '28'],
            ['city_id' => '5', 'name' => 'Pruhso', 'name_mm' => 'ပြုဆို', 'id' => '29'],
            ['city_id' => '5', 'name' => 'Shadaw', 'name_mm' => 'ရှားတော်', 'id' => '30'],
            ['city_id' => '5', 'name' => 'Bawlakhe', 'name_mm' => 'ဘော်လခဲ', 'id' => '31'],
            ['city_id' => '5', 'name' => 'Hpasawng', 'name_mm' => 'ဖားဆောင်', 'id' => '32'],
            ['city_id' => '5', 'name' => 'Maisal', 'name_mm' => 'မိုးစား', 'id' => '33'],
            ['city_id' => '6', 'name' => 'Hpa-an', 'name_mm' => 'ဘားအံ', 'id' => '34'],
            ['city_id' => '6', 'name' => 'Hlaingbwe (Hlinebwe)', 'name_mm' => 'လှိုင်းဘွဲ့ (လှိုင်းဘွဲ့)', 'id' => '35'],
            ['city_id' => '6', 'name' => 'Papun (Phapun)', 'name_mm' => 'ဖာပွန် (ဖာပွန်)', 'id' => '36'],
            ['city_id' => '6', 'name' => 'Thandang', 'name_mm' => 'သံတန်း', 'id' => '37'],
            ['city_id' => '6', 'name' => 'Thandanggyi (Thantaunggyi)', 'name_mm' => 'သံတန်းကြီး (သံတောင်ကြီး)', 'id' => '38'],
            ['city_id' => '6', 'name' => 'Myawaddy (Myawadi)', 'name_mm' => 'မြဝတီ (မြဝတီ)', 'id' => '39'],
            ['city_id' => '6', 'name' => 'Kawkareik (Kawkareit)', 'name_mm' => 'ကော့ကရိတ် (ကော့ကရောက်)', 'id' => '40'],
            ['city_id' => '6', 'name' => 'Kyeikdon', 'name_mm' => 'ကျိပ်တုံ', 'id' => '41'],
            ['city_id' => '6', 'name' => 'Kyain Seikgyi (Kyainseikkyi)', 'name_mm' => 'ကျိုင်းဆိပ်ကြီး (ကျိုင်းဆိပ်ကျီး)', 'id' => '42'],
            ['city_id' => '6', 'name' => 'Payathonsu (Hpayarthonesu)', 'name_mm' => 'ဖရသုံးဆု (ဖရသုံးဆု)', 'id' => '43'],
            ['city_id' => '3', 'name' => 'Tedim', 'name_mm' => 'တီးတိမ်', 'id' => '44'],
            ['city_id' => '3', 'name' => 'Tonzang', 'name_mm' => 'တွန်းဇန်', 'id' => '45'],
            ['city_id' => '3', 'name' => 'Falam (Phalam)', 'name_mm' => 'ဖလမ်း (ဖလမ်း)', 'id' => '46'],
            ['city_id' => '3', 'name' => 'Hakha (Haka, Harkhar)', 'name_mm' => 'ဟားခါ (ဟားခါ, ဟားခါး)', 'id' => '47'],
            ['city_id' => '3', 'name' => 'Thantlang (Htantlang)', 'name_mm' => 'ထန်တလန် (ထန်လန်)', 'id' => '48'],
            ['city_id' => '3', 'name' => 'Kanpetlet (Kanpatlat)', 'name_mm' => 'ကန်ပက်လက် (ကန်ပလက်)', 'id' => '49'],
            ['city_id' => '3', 'name' => 'Matupi (Matupe)', 'name_mm' => 'မတူပီ (မတုပီ)', 'id' => '50'],
            ['city_id' => '3', 'name' => 'Mindat (Minthet)', 'name_mm' => 'မင်းတပ် (မင်းသက်)', 'id' => '51'],
            ['city_id' => '3', 'name' => 'Paletwa', 'name_mm' => 'ပလက်ဝ (ပလက်ဝ)', 'id' => '52'],
            ['city_id' => '3', 'name' => 'Cikha', 'name_mm' => 'စိုခါ', 'id' => '53'],
            ['city_id' => '3', 'name' => 'Rih Khawdar', 'name_mm' => 'ရီခေါတာ', 'id' => '54'],
            ['city_id' => '3', 'name' => 'Razua (Yay Zwar)', 'name_mm' => 'ရာဇွာ (ရေဇွာ)', 'id' => '55'],
            ['city_id' => '3', 'name' => 'Sami (Samee)', 'name_mm' => 'ဆားမီ', 'id' => '56'],
            ['city_id' => '9', 'name' => 'Mawlamyaing(Moulmein)', 'name_mm' => 'မော်လမြိုင် (မော်လမြိုင်)', 'id' => '57'],
            ['city_id' => '9', 'name' => 'Bilin', 'name_mm' => 'ဘီလင်', 'id' => '58'],
            ['city_id' => '9', 'name' => 'Kyaikmaraw', 'name_mm' => 'ကျိုက်မရော', 'id' => '59'],
            ['city_id' => '9', 'name' => 'Chaungzon', 'name_mm' => 'ချောင်းဇုန်', 'id' => '60'],
            ['city_id' => '9', 'name' => 'Thanbyuzayat', 'name_mm' => 'သံဖြူဇရပ်', 'id' => '61'],
            ['city_id' => '9', 'name' => 'Kyaikkami', 'name_mm' => 'ကျိုက်ကမီ', 'id' => '62'],
            ['city_id' => '9', 'name' => 'Mudon', 'name_mm' => 'မုဒုံ', 'id' => '63'],
            ['city_id' => '9', 'name' => 'Ye', 'name_mm' => 'ရေဦး', 'id' => '64'],
            ['city_id' => '9', 'name' => 'Thaton', 'name_mm' => 'သထုံ', 'id' => '65'],
            ['city_id' => '9', 'name' => 'Paung', 'name_mm' => 'ပေါင်', 'id' => '66'],
            ['city_id' => '9', 'name' => 'Kyaikto', 'name_mm' => 'ကျိုက်တို', 'id' => '67'],
            ['city_id' => '9', 'name' => 'Mottama', 'name_mm' => 'မို့တမ', 'id' => '68'],
            ['city_id' => '10', 'name' => 'Sittwe', 'name_mm' => 'စစ်တွေ', 'id' => '69'],
            ['city_id' => '10', 'name' => 'Ann', 'name_mm' => 'အမ်း', 'id' => '70'],
            ['city_id' => '10', 'name' => 'Buthidaung', 'name_mm' => 'ဘူးသီးတောင်', 'id' => '71'],
            ['city_id' => '10', 'name' => 'Dalet (Dalat)', 'name_mm' => 'ဓာလတ် (ဓာလပ်)', 'id' => '72'],
            ['city_id' => '10', 'name' => 'Gwa', 'name_mm' => 'ဂွ', 'id' => '73'],
            ['city_id' => '10', 'name' => 'Kyaukpyu', 'name_mm' => 'ကျောက်ဖြူ', 'id' => '74'],
            ['city_id' => '10', 'name' => 'Kyauktaw', 'name_mm' => 'ကျောက်တော', 'id' => '75'],
            ['city_id' => '10', 'name' => 'Kyeintali', 'name_mm' => 'ကြိုင်တယ်', 'id' => '76'],
            ['city_id' => '10', 'name' => 'Manaung', 'name_mm' => 'မာန်အောင်', 'id' => '77'],
            ['city_id' => '10', 'name' => 'Maungdaw', 'name_mm' => 'မောင်တော', 'id' => '78'],
            ['city_id' => '10', 'name' => 'Minbya', 'name_mm' => 'မင်းပြား', 'id' => '79'],
            ['city_id' => '10', 'name' => 'Mrauk U', 'name_mm' => 'မြောက်ဦး', 'id' => '80'],
            ['city_id' => '10', 'name' => 'Myebon', 'name_mm' => 'မြေပုံ', 'id' => '81'],
            ['city_id' => '10', 'name' => 'Ngapali', 'name_mm' => 'ငပလီ', 'id' => '82'],
            ['city_id' => '10', 'name' => 'Pauktaw', 'name_mm' => 'ပေါက်တော', 'id' => '83'],
            ['city_id' => '10', 'name' => 'Ponnagyun', 'name_mm' => 'ပုဏ္ဏားကျွန်း', 'id' => '84'],
            ['city_id' => '10', 'name' => 'Ramree', 'name_mm' => 'ရမ်းဗြဲ', 'id' => '85'],
            ['city_id' => '10', 'name' => 'Rathedaung', 'name_mm' => 'ရသောင်း', 'id' => '86'],
            ['city_id' => '10', 'name' => 'Thandwe', 'name_mm' => 'သံတွဲ', 'id' => '87'],
            ['city_id' => '10', 'name' => 'Toungup', 'name_mm' => 'တောင်တုတ်', 'id' => '88'],
            ['city_id' => '12', 'name' => 'Toungup', 'name_mm' => 'တောင်တုတ်', 'id' => '89'],
            ['city_id' => '12', 'name' => 'Aungban', 'name_mm' => 'အောင်ဘန်', 'id' => '90'],
            ['city_id' => '12', 'name' => 'Toungup', 'name_mm' => 'တောင်အပ်', 'id' => '91'],
            ['city_id' => '12', 'name' => 'Ayetharyar', 'name_mm' => 'အေးသာရာ', 'id' => '92'],
            ['city_id' => '12', 'name' => 'Chinshwehaw', 'name_mm' => 'ချဉ်ရွေဟော', 'id' => '93'],
            ['city_id' => '12', 'name' => 'Ho-pin', 'name_mm' => 'ဟိုပင်', 'id' => '94'],
            ['city_id' => '12', 'name' => 'Hopang', 'name_mm' => 'ဟိုပန်', 'id' => '95'],
            ['city_id' => '12', 'name' => 'Hopong', 'name_mm' => 'ဟိုပုံး', 'id' => '96'],
            ['city_id' => '12', 'name' => 'Hseni', 'name_mm' => 'ဆယ်နီ', 'id' => '97'],
            ['city_id' => '12', 'name' => 'Hsi Hseng', 'name_mm' => 'ဆီဆိုင်', 'id' => '98'],
            ['city_id' => '12', 'name' => 'Hsipaw', 'name_mm' => 'သီပေ', 'id' => '99'],
            ['city_id' => '12', 'name' => 'Kalaw', 'name_mm' => 'ကော့လော', 'id' => '100'],
            ['city_id' => '12', 'name' => 'Kengtong', 'name_mm' => 'ကျိုင်းတုံ', 'id' => '101'],
            ['city_id' => '12', 'name' => 'Kunhing', 'name_mm' => 'ကွန်ဟိုင်', 'id' => '102'],
            ['city_id' => '12', 'name' => 'Kunlong', 'name_mm' => 'ကွမ်းလုံ', 'id' => '103'],
            ['city_id' => '12', 'name' => 'Kutkai', 'name_mm' => 'ကွတ်ခိုင်', 'id' => '104'],
            ['city_id' => '12', 'name' => 'Kyaukme', 'name_mm' => 'ကျောက်မဲ', 'id' => '105'],
            ['city_id' => '12', 'name' => 'Kyethi', 'name_mm' => 'ကြည့်သီ', 'id' => '106'],
            ['city_id' => '12', 'name' => 'Lai-Hka', 'name_mm' => 'လဲချာ', 'id' => '107'],
            ['city_id' => '12', 'name' => 'Langkho', 'name_mm' => 'လင်းခေး', 'id' => '108'],
            ['city_id' => '12', 'name' => 'Lashio', 'name_mm' => 'လားရှို', 'id' => '109'],
            ['city_id' => '12', 'name' => 'Lawksawk', 'name_mm' => 'လောက်ဆောက်', 'id' => '110'],
            ['city_id' => '12', 'name' => 'Loilen', 'name_mm' => 'လွိုင်းလင်', 'id' => '111'],
            ['city_id' => '12', 'name' => 'Laukkaing', 'name_mm' => 'လောက်ချိုင်', 'id' => '112'],
            ['city_id' => '12', 'name' => 'Mabein', 'name_mm' => 'မာပိန်', 'id' => '113'],
            ['city_id' => '12', 'name' => 'Mantong', 'name_mm' => 'မန်တုံ', 'id' => '114'],
            ['city_id' => '12', 'name' => 'Mawkmai', 'name_mm' => 'မောက်မယ်', 'id' => '115'],
            ['city_id' => '12', 'name' => 'Mine Hsu', 'name_mm' => 'မိုင်းဆုး', 'id' => '116'],
            ['city_id' => '12', 'name' => 'Mine Khet', 'name_mm' => 'မိုင်းခက်', 'id' => '117'],
            ['city_id' => '12', 'name' => 'Mine Kung', 'name_mm' => 'မိုင်းကုံ', 'id' => '118'],
            ['city_id' => '12', 'name' => 'Mine Nai', 'name_mm' => 'မိုင်းနိုင်', 'id' => '119'],
            ['city_id' => '12', 'name' => 'Mine Pan', 'name_mm' => 'မိုင်းပန်', 'id' => '120'],
            ['city_id' => '12', 'name' => 'Mine Ping', 'name_mm' => 'မိုင်းပင်', 'id' => '121'],
            ['city_id' => '12', 'name' => 'Mine Tong', 'name_mm' => 'မိုင်းတုံ', 'id' => '122'],
            ['city_id' => '12', 'name' => 'Mine Yang', 'name_mm' => 'မိုင်းယန်း', 'id' => '123'],
            ['city_id' => '12', 'name' => 'Mine Yawng', 'name_mm' => 'မိုင်းယောင်', 'id' => '124'],
            ['city_id' => '12', 'name' => 'Mine Hsat', 'name_mm' => 'မိုင်းဆတ်', 'id' => '125'],
            ['city_id' => '12', 'name' => 'Mineko', 'name_mm' => 'မိုင်းကို', 'id' => '126'],
            ['city_id' => '12', 'name' => 'Minemit', 'name_mm' => 'မိုင်းမက်', 'id' => '127'],
            ['city_id' => '12', 'name' => 'Mineyai', 'name_mm' => 'မိုင်းရိုင်', 'id' => '128'],
            ['city_id' => '12', 'name' => 'Mu Se', 'name_mm' => 'မူဆယ်', 'id' => '129'],
            ['city_id' => '12', 'name' => 'Namhsan', 'name_mm' => 'နမ့်ဆန်', 'id' => '130'],
            ['city_id' => '1', 'name' => 'Namtu', 'name_mm' => 'နမ့်တူ', 'id' => '131'],
            ['city_id' => '12', 'name' => 'Nanhkan', 'name_mm' => 'နမ့်ခန်း', 'id' => '132'],
            ['city_id' => '12', 'name' => 'Nansang', 'name_mm' => 'နမ့်စန်း', 'id' => '133'],
            ['city_id' => '12', 'name' => 'Nawnghkio', 'name_mm' => 'နောင်ချို', 'id' => '134'],
            ['city_id' => '12', 'name' => 'Nyaungshwe', 'name_mm' => 'ညောင်ရွှေ', 'id' => '135'],
            ['city_id' => '12', 'name' => 'Pang Long', 'name_mm' => 'ပန်လုံ', 'id' => '136'],
            ['city_id' => '12', 'name' => 'Pekon', 'name_mm' => 'ပဲခူး', 'id' => '137'],
            ['city_id' => '12', 'name' => 'Pindaya', 'name_mm' => 'ပင်းတယ', 'id' => '138'],
            ['city_id' => '12', 'name' => 'Pinlaung', 'name_mm' => 'ပင်လောင်း', 'id' => '139'],
            ['city_id' => '12', 'name' => 'Tant Yan', 'name_mm' => 'ထန်းယန်း', 'id' => '140'],
            ['city_id' => '12', 'name' => 'Taunggyi', 'name_mm' => 'တောင်ကြီး', 'id' => '141'],
            ['city_id' => '12', 'name' => 'Techilelk', 'name_mm' => 'တက်ချီလက်', 'id' => '142'],
            ['city_id' => '12', 'name' => 'Ywangan', 'name_mm' => 'ရွာငံ', 'id' => '143'],
            ['city_id' => '11', 'name' => 'Ayadaw', 'name_mm' => 'အရာတော်', 'id' => '144'],
            ['city_id' => '11', 'name' => 'Banmauk', 'name_mm' => 'ဗန်းမောက်', 'id' => '145'],
            ['city_id' => '11', 'name' => 'Budalin', 'name_mm' => 'ဘုတလင်', 'id' => '146'],
            ['city_id' => '11', 'name' => 'Chaung', 'name_mm' => 'ချောင်း', 'id' => '147'],
            ['city_id' => '11', 'name' => 'Dabayin', 'name_mm' => 'ဒဘရင်', 'id' => '148'],
            ['city_id' => '11', 'name' => 'Hkamti', 'name_mm' => 'ခန္တီ', 'id' => '149'],
            ['city_id' => '11', 'name' => 'Homalin', 'name_mm' => 'ဟုမ္မလင်း', 'id' => '150'],
            ['city_id' => '11', 'name' => 'Htigyaing', 'name_mm' => 'ထီးချိုင့်', 'id' => '151'],
            ['city_id' => '11', 'name' => 'Indaw', 'name_mm' => 'အင်းတော်', 'id' => '152'],
            ['city_id' => '11', 'name' => 'Kalaymyo', 'name_mm' => 'ကလေးမြို့', 'id' => '153'],
            ['city_id' => '11', 'name' => 'Kalewa', 'name_mm' => 'ကလေးဝ', 'id' => '154'],
            ['city_id' => '11', 'name' => 'Kanbalu', 'name_mm' => 'ကန်းဘလူ', 'id' => '155'],
            ['city_id' => '11', 'name' => 'Kani', 'name_mm' => 'ကနီ', 'id' => '156'],
            ['city_id' => '11', 'name' => 'Katha', 'name_mm' => 'ကသာ', 'id' => '157'],
            ['city_id' => '11', 'name' => 'Kawlin', 'name_mm' => 'ကောလင်း', 'id' => '158'],
            ['city_id' => '11', 'name' => 'Khin U', 'name_mm' => 'ခင်ဦး', 'id' => '159'],
            ['city_id' => '11', 'name' => 'Kyadet', 'name_mm' => 'ကြားတက်', 'id' => '160'],
            ['city_id' => '11', 'name' => 'Kyunhla', 'name_mm' => 'ကွမ်လာ', 'id' => '161'],
            ['city_id' => '11', 'name' => 'Mawlaik', 'name_mm' => 'မော်လိုက်', 'id' => '162'],
            ['city_id' => '11', 'name' => 'Mingun', 'name_mm' => 'မင်းကွန်း', 'id' => '163'],
            ['city_id' => '11', 'name' => 'Monywa', 'name_mm' => 'မုံရွာ', 'id' => '164'],
            ['city_id' => '11', 'name' => 'Myaung', 'name_mm' => 'မြောင်', 'id' => '165'],
            ['city_id' => '11', 'name' => 'Myinmu', 'name_mm' => 'မြင်းမူ', 'id' => '166'],
            ['city_id' => '11', 'name' => 'Pale', 'name_mm' => 'ပုလဲ', 'id' => '167'],
            ['city_id' => '11', 'name' => 'Paungbyin', 'name_mm' => 'ပေါင်းပြင်', 'id' => '168'],
            ['city_id' => '11', 'name' => 'Pinlebu', 'name_mm' => 'ပင်လည်ဘူး', 'id' => '169'],
            ['city_id' => '11', 'name' => 'Sagaing', 'name_mm' => 'စစ်ကိုင်း', 'id' => '170'],
            ['city_id' => '11', 'name' => 'Salingyi', 'name_mm' => 'ဆားလင်း', 'id' => '171'],
            ['city_id' => '11', 'name' => 'Shwebo', 'name_mm' => 'ရွှေဘို', 'id' => '172'],
            ['city_id' => '11', 'name' => 'Tamu', 'name_mm' => 'တမူ', 'id' => '173'],
            ['city_id' => '11', 'name' => 'Tantsal', 'name_mm' => 'တန့်ဆဲ', 'id' => '174'],
            ['city_id' => '11', 'name' => 'Wetlet', 'name_mm' => 'ဝက်လက်', 'id' => '175'],
            ['city_id' => '11', 'name' => 'Wuntho', 'name_mm' => 'ဝန်းသို', 'id' => '176'],
            ['city_id' => '11', 'name' => 'Ye-U', 'name_mm' => 'ရေဦး', 'id' => '177'],
            ['city_id' => '11', 'name' => 'Yinmabin', 'name_mm' => 'ယင်းမပင်', 'id' => '178'],
            ['city_id' => '11', 'name' => 'Mungnii', 'name_mm' => 'မွန်နီး', 'id' => '179'],
            ['city_id' => '13', 'name' => 'Dawei', 'name_mm' => 'ထားဝယ်', 'id' => '180'],
            ['city_id' => '13', 'name' => 'Launglon', 'name_mm' => 'လောင်းလုံ', 'id' => '181'],
            ['city_id' => '13', 'name' => 'Thayetchaung', 'name_mm' => 'သရက်ချောင်း', 'id' => '182'],
            ['city_id' => '13', 'name' => 'Yebyu', 'name_mm' => 'ရေဖြူ', 'id' => '183'],
            ['city_id' => '13', 'name' => 'Myeik', 'name_mm' => 'မြိတ်', 'id' => '184'],
            ['city_id' => '13', 'name' => 'Kyunsu', 'name_mm' => 'ကျွန်းစု', 'id' => '185'],
            ['city_id' => '13', 'name' => 'Palaw', 'name_mm' => 'ပုလော', 'id' => '186'],
            ['city_id' => '13', 'name' => 'Taninthayi', 'name_mm' => 'တနင်္သာရီ', 'id' => '187'],
            ['city_id' => '13', 'name' => 'Kawthoung', 'name_mm' => 'ကော့သောင်း', 'id' => '188'],
            ['city_id' => '13', 'name' => 'Bokpyin', 'name_mm' => 'ဘုတ်ပြင်', 'id' => '189'],
            ['city_id' => '2', 'name' => 'Bago', 'name_mm' => 'ပဲခူး', 'id' => '190'],
            ['city_id' => '2', 'name' => 'Thanatpin', 'name_mm' => 'သနပ်ပင်', 'id' => '191'],
            ['city_id' => '2', 'name' => 'Kawa', 'name_mm' => 'ကဝ', 'id' => '192'],
            ['city_id' => '2', 'name' => 'Waw', 'name_mm' => 'ဝေါ', 'id' => '193'],
            ['city_id' => '2', 'name' => 'Nyaunglebin', 'name_mm' => 'ညောင်လေးပင်', 'id' => '194'],
            ['city_id' => '2', 'name' => 'Madauk', 'name_mm' => 'မဒေါက်', 'id' => '195'],
            ['city_id' => '2', 'name' => 'Pyuntaza', 'name_mm' => 'ပျွန်တန်းဇာ', 'id' => '196'],
            ['city_id' => '2', 'name' => 'Kyauktaga', 'name_mm' => 'ကျောက်တံခါ', 'id' => '197'],
            ['city_id' => '2', 'name' => 'Pennwegone', 'name_mm' => 'ပင်ဝေဂုံး', 'id' => '198'],
            ['city_id' => '2', 'name' => 'Daik-U', 'name_mm' => 'ဒိုက်ဦး', 'id' => '199'],
            ['city_id' => '2', 'name' => 'Shwegyin', 'name_mm' => 'ရွှေကျင်', 'id' => '200'],
            ['city_id' => '2', 'name' => 'Taungoo', 'name_mm' => 'တောင်ငူ', 'id' => '201'],
            ['city_id' => '2', 'name' => 'Kututmatyi', 'name_mm' => 'ကွတ်တမ္တီ', 'id' => '202'],
            ['city_id' => '2', 'name' => 'Yaytarshay', 'name_mm' => 'ရေတာရှည်', 'id' => '203'],
            ['city_id' => '2', 'name' => 'Kyaukkyi', 'name_mm' => 'ကျောက်ကြီး', 'id' => '204'],
            ['city_id' => '2', 'name' => 'Phyu', 'name_mm' => 'ဖြူ', 'id' => '205'],
            ['city_id' => '2', 'name' => 'Oktwin', 'name_mm' => 'အုတ်တွင်း', 'id' => '206'],
            ['city_id' => '2', 'name' => 'Htantabin', 'name_mm' => 'ထန်းတပင်', 'id' => '207'],
            ['city_id' => '2', 'name' => 'Pyay', 'name_mm' => 'ပြည်', 'id' => '208'],
            ['city_id' => '2', 'name' => 'Paukkhaung', 'name_mm' => 'ပေါက်ခေါင်', 'id' => '209'],
            ['city_id' => '2', 'name' => 'Padaung', 'name_mm' => 'ပန်းတောင်', 'id' => '210'],
            ['city_id' => '2', 'name' => 'Paungde', 'name_mm' => 'ပေါင်းတည်', 'id' => '211'],
            ['city_id' => '2', 'name' => 'Thegon', 'name_mm' => 'သဲကုန်', 'id' => '212'],
            ['city_id' => '2', 'name' => 'Shwedaung', 'name_mm' => 'ရွှေတောင်', 'id' => '213'],
            ['city_id' => '2', 'name' => 'Thayarwaddy', 'name_mm' => 'သာယာဝတီ', 'id' => '214'],
            ['city_id' => '2', 'name' => 'Thonze', 'name_mm' => 'သုံးဆယ်', 'id' => '215'],
            ['city_id' => '2', 'name' => 'Letpadan', 'name_mm' => 'လက်ပတန်း', 'id' => '216'],
            ['city_id' => '2', 'name' => 'Minhla', 'name_mm' => 'မင်းလှ', 'id' => '217'],
            ['city_id' => '2', 'name' => 'Okpo', 'name_mm' => 'အုတ်ပိုင်', 'id' => '218'],
            ['city_id' => '2', 'name' => 'Zigon', 'name_mm' => 'ဇင်းကုန်း', 'id' => '219'],
            ['city_id' => '2', 'name' => 'Nattalin', 'name_mm' => 'နတ်တလင်း', 'id' => '220'],
            ['city_id' => '2', 'name' => 'Monyo', 'name_mm' => 'မုံရိုး', 'id' => '221'],
            ['city_id' => '2', 'name' => 'Gyobingauk', 'name_mm' => 'ကြို့ပင်ကောက်', 'id' => '222'],
            ['city_id' => '7', 'name' => 'Magwe', 'name_mm' => 'မကွေ', 'id' => '223'],
            ['city_id' => '7', 'name' => 'Allanmyo (Aunglan, Myaydo)', 'name_mm' => 'အလံမြို (အောင်လံ, မြေတို)', 'id' => '224'],
            ['city_id' => '7', 'name' => 'Chauck', 'name_mm' => 'ချောက်', 'id' => '225'],
            ['city_id' => '7', 'name' => 'Gangaw', 'name_mm' => 'ဂန့်ဂေါ', 'id' => '226'],
            ['city_id' => '7', 'name' => 'Kamma', 'name_mm' => 'ကန်မာ', 'id' => '227'],
            ['city_id' => '7', 'name' => 'Minbu', 'name_mm' => 'မင်းဘူး', 'id' => '228'],
            ['city_id' => '7', 'name' => 'Mindon', 'name_mm' => 'မင်းတုံ', 'id' => '229'],
            ['city_id' => '7', 'name' => 'Minhla', 'name_mm' => 'မင်းလှ', 'id' => '230'],
            ['city_id' => '7', 'name' => 'Myaing', 'name_mm' => 'မြိုင်', 'id' => '231'],
            ['city_id' => '7', 'name' => 'Myothit', 'name_mm' => 'မြို့သစ်', 'id' => '232'],
            ['city_id' => '7', 'name' => 'Natmauk', 'name_mm' => 'နတ်မောက်', 'id' => '233'],
            ['city_id' => '7', 'name' => 'Ngape', 'name_mm' => 'ငဖဲ', 'id' => '234'],
            ['city_id' => '7', 'name' => 'Pakokku', 'name_mm' => 'ပခုက္ကူ', 'id' => '235'],
            ['city_id' => '7', 'name' => 'Pauk', 'name_mm' => 'ပေါက်', 'id' => '236'],
            ['city_id' => '7', 'name' => 'Pwintbyu', 'name_mm' => 'ပွင့်ဖြူ', 'id' => '237'],
            ['city_id' => '7', 'name' => 'Sagu', 'name_mm' => 'စကူ', 'id' => '238'],
            ['city_id' => '7', 'name' => 'Salin', 'name_mm' => 'စလင်း', 'id' => '239'],
            ['city_id' => '7', 'name' => 'Swar', 'name_mm' => 'ဆွာ', 'id' => '240'],
            ['city_id' => '7', 'name' => 'Seikphyu', 'name_mm' => 'ဆိပ်ဖြူ', 'id' => '241'],
            ['city_id' => '7', 'name' => 'Sidoktaya', 'name_mm' => 'စတုတ္ထရာ', 'id' => '242'],
            ['city_id' => '7', 'name' => 'Sinbyugyun', 'name_mm' => 'စင်းပြုကျွန်း', 'id' => '243'],
            ['city_id' => '7', 'name' => 'Taungdwingyi', 'name_mm' => 'တောင်တွင်းကြီး', 'id' => '244'],
            ['city_id' => '7', 'name' => 'Thayet', 'name_mm' => 'သရက်', 'id' => '245'],
            ['city_id' => '7', 'name' => 'Tilin', 'name_mm' => 'ထီးလင်း', 'id' => '246'],
            ['city_id' => '14', 'name' => 'Ahlon', 'name_mm' => 'အလုံ', 'id' => '248'],
            ['city_id' => '14', 'name' => 'Bahan', 'name_mm' => 'ဗဟန်', 'id' => '249'],
            ['city_id' => '14', 'name' => 'Botataung', 'name_mm' => 'ဗိုလ်တောင်', 'id' => '250'],
            ['city_id' => '14', 'name' => 'Cocokyun', 'name_mm' => 'ကိုကိုးကျွန်း', 'id' => '251'],
            ['city_id' => '14', 'name' => 'Dagon', 'name_mm' => 'ဒဂုံ', 'id' => '252'],
            ['city_id' => '14', 'name' => 'Dagon Myothit(East)', 'name_mm' => 'ဒဂုံမြို့သစ်(အရှေ့)', 'id' => '253'],
            ['city_id' => '14', 'name' => 'Dagon Myothit(North)', 'name_mm' => 'ဒဂုံမြို့သစ် (မြောက်)', 'id' => '254'],
            ['city_id' => '14', 'name' => 'Dagon Myothit(Seikkan)', 'name_mm' => 'ဒဂုံမြို့သစ် (ဆိပ်ကမ်း)', 'id' => '255'],
            ['city_id' => '14', 'name' => 'Dagon Myothit(South)', 'name_mm' => 'ဒဂုံမြို့သစ် (တောင်)', 'id' => '256'],
            ['city_id' => '14', 'name' => 'Dala', 'name_mm' => 'ဒလ', 'id' => '257'],
            ['city_id' => '14', 'name' => 'Dawbon', 'name_mm' => 'ဒေါပုံ', 'id' => '258'],
            ['city_id' => '14', 'name' => 'Hlaing', 'name_mm' => 'လှိုင်', 'id' => '259'],
            ['city_id' => '14', 'name' => 'Hlaingtharya', 'name_mm' => 'လှိုင်သာယာ', 'id' => '260'],
            ['city_id' => '14', 'name' => 'Hlegu', 'name_mm' => 'လှည်းကူး', 'id' => '261'],
            ['city_id' => '14', 'name' => 'Hmawbi', 'name_mm' => 'မှော်ဘီ', 'id' => '262'],
            ['city_id' => '14', 'name' => 'Htantabin', 'name_mm' => 'ထန်းတပင်', 'id' => '263'],
            ['city_id' => '14', 'name' => 'Insein', 'name_mm' => 'အင်းစိန်', 'id' => '264'],
            ['city_id' => '14', 'name' => 'Kamaryut', 'name_mm' => 'ကမာရွတ်', 'id' => '265'],
            ['city_id' => '14', 'name' => 'Kayan', 'name_mm' => 'ကရမ်', 'id' => '266'],
            ['city_id' => '14', 'name' => 'Kawhmu', 'name_mm' => 'ကော့မှူ', 'id' => '267'],
            ['city_id' => '14', 'name' => 'Kungyangon', 'name_mm' => 'ကွမ်းခြံ', 'id' => '268'],
            ['city_id' => '14', 'name' => 'Kyauktada', 'name_mm' => 'ကျောက်တံတား', 'id' => '269'],
            ['city_id' => '14', 'name' => 'Kyauktan', 'name_mm' => 'ကျောက်တန်း', 'id' => '270'],
            ['city_id' => '14', 'name' => 'Kyeemyindaing', 'name_mm' => 'ကြည့်မြင်တိုင်', 'id' => '271'],
            ['city_id' => '14', 'name' => 'Lanmadaw', 'name_mm' => 'လမ်းမတော်', 'id' => '272'],
            ['city_id' => '14', 'name' => 'Latha', 'name_mm' => 'လသာ', 'id' => '273'],
            ['city_id' => '14', 'name' => 'Mayangone', 'name_mm' => 'မရမ်းကုန်း', 'id' => '274'],
            ['city_id' => '14', 'name' => 'Mingaladon', 'name_mm' => 'မင်္ဂလာတုံ', 'id' => '275'],
            ['city_id' => '14', 'name' => 'Mingalartaungnyunt', 'name_mm' => 'မင်္ဂလာတောင်ညွန့်', 'id' => '276'],
            ['city_id' => '14', 'name' => 'North Okkalapa', 'name_mm' => 'မြောက်ဥက္ကလာပ', 'id' => '277'],
            ['city_id' => '14', 'name' => 'Pabedan', 'name_mm' => 'ပန်းဘဲတန်း', 'id' => '278'],
            ['city_id' => '14', 'name' => 'Pazundaung', 'name_mm' => 'ပုဇွန်တောင်', 'id' => '279'],
            ['city_id' => '14', 'name' => 'Sanchaung', 'name_mm' => 'ဆမ်းချောင်း', 'id' => '280'],
            ['city_id' => '14', 'name' => 'Seikgyikanaungto', 'name_mm' => 'ဆိပ်ကြီးကန်နောင်တို', 'id' => '281'],
            ['city_id' => '14', 'name' => 'Seikkan', 'name_mm' => 'ဆိပ်ကမ်း', 'id' => '282'],
            ['city_id' => '14', 'name' => 'Shwepyithar', 'name_mm' => 'ရွှေပြည်သာ', 'id' => '283'],
            ['city_id' => '14', 'name' => 'South Okkalapa', 'name_mm' => 'တောင်ဥက္ကလာပ', 'id' => '284'],
            ['city_id' => '14', 'name' => 'Taikkyi', 'name_mm' => 'တိုက်ကြီး', 'id' => '285'],
            ['city_id' => '14', 'name' => 'Tamwe', 'name_mm' => 'တာမွေ', 'id' => '286'],
            ['city_id' => '14', 'name' => 'Thaketa', 'name_mm' => 'သာကေတ', 'id' => '287'],
            ['city_id' => '14', 'name' => 'Thanlyin', 'name_mm' => 'သန်လျင်', 'id' => '288'],
            ['city_id' => '14', 'name' => 'Thingangkuun', 'name_mm' => 'သင်္ဃန်းကွုန်', 'id' => '289'],
            ['city_id' => '14', 'name' => 'Thongwa', 'name_mm' => 'သုံးခွ', 'id' => '290'],
            ['city_id' => '14', 'name' => 'Twantay', 'name_mm' => 'တွံတေး', 'id' => '291'],
            ['city_id' => '14', 'name' => 'Yankin', 'name_mm' => 'ရန်ကင်း', 'id' => '292'],
            ['city_id' => '1', 'name' => 'Pathein', 'name_mm' => 'ပုသိမ်', 'id' => '293'],
            ['city_id' => '1', 'name' => 'Kangyidaut', 'name_mm' => 'ကန်ကြီးတော်', 'id' => '294'],
            ['city_id' => '1', 'name' => 'Thabaung', 'name_mm' => 'သာပေါင်း', 'id' => '295'],
            ['city_id' => '1', 'name' => 'Ngapudaw', 'name_mm' => 'ငပုတော်', 'id' => '296'],
            ['city_id' => '1', 'name' => 'Haigyi Island', 'name_mm' => 'ဟိုင်းကျွီးကျွန်း', 'id' => '297'],
            ['city_id' => '1', 'name' => 'Kyonpyaw', 'name_mm' => 'ကျုံပျော်', 'id' => '298'],
            ['city_id' => '1', 'name' => 'Yekyi', 'name_mm' => 'ရေကြည်', 'id' => '299'],
            ['city_id' => '1', 'name' => 'Kyaunggon', 'name_mm' => 'ကျောင်းကုန်း', 'id' => '300'],
            ['city_id' => '1', 'name' => 'Hinthada', 'name_mm' => 'ဟင်္သာတ', 'id' => '301'],
            ['city_id' => '1', 'name' => 'Zalun', 'name_mm' => 'ဇလွန်', 'id' => '302'],
            ['city_id' => '1', 'name' => 'Lemyethna', 'name_mm' => 'လေးမျက်နှာ', 'id' => '303'],
            ['city_id' => '1', 'name' => 'Myan Aung', 'name_mm' => 'မြန်အောင်', 'id' => '304'],
            ['city_id' => '1', 'name' => 'Kanaung', 'name_mm' => 'ကန်အောင်', 'id' => '305'],
            ['city_id' => '1', 'name' => 'Kyangin', 'name_mm' => 'ကြံခင်း', 'id' => '306'],
            ['city_id' => '1', 'name' => 'Ingapu', 'name_mm' => 'အင်္ကပု', 'id' => '307'],
            ['city_id' => '1', 'name' => 'Myaungmya', 'name_mm' => 'မြောင်းမြ', 'id' => '308'],
            ['city_id' => '1', 'name' => 'Einme', 'name_mm' => 'အိမ်မဲ', 'id' => '309'],
            ['city_id' => '1', 'name' => 'Letputta', 'name_mm' => 'လက်ဖတ်တာ', 'id' => '310'],
            ['city_id' => '1', 'name' => 'Wakema', 'name_mm' => 'ဝါးကောမ', 'id' => '311'],
            ['city_id' => '1', 'name' => 'Mawlamyinegyun', 'name_mm' => 'မော်လမြိုင်းကျွန်း', 'id' => '312'],
            ['city_id' => '1', 'name' => 'Maubin', 'name_mm' => 'မအူပင်', 'id' => '313'],
            ['city_id' => '1', 'name' => 'Pantanaw', 'name_mm' => 'ပန်းတနော်', 'id' => '314'],
            ['city_id' => '1', 'name' => 'Nyaungdon', 'name_mm' => 'ညောင်တန်း', 'id' => '315'],
            ['city_id' => '1', 'name' => 'Danubyu', 'name_mm' => 'ဓနုဖြူ', 'id' => '316'],
            ['city_id' => '1', 'name' => 'Pyapon', 'name_mm' => 'ဖျာပုံ', 'id' => '317'],
            ['city_id' => '1', 'name' => 'Bogale', 'name_mm' => 'ဘိုကလေး', 'id' => '318'],
            ['city_id' => '1', 'name' => 'Kyaiklat', 'name_mm' => 'ကျိုက်လတ်', 'id' => '319'],
            ['city_id' => '1', 'name' => 'Dedaye', 'name_mm' => 'ဒေးဒရဲ', 'id' => '320'],
            ['city_id' => '8', 'name' => 'Amarapura', 'name_mm' => 'အမရပူရ', 'id' => '321'],
            ['city_id' => '8', 'name' => 'Aungmyaythazan', 'name_mm' => 'အောင်မြေသာ့ဇံ', 'id' => '322'],
            ['city_id' => '8', 'name' => 'Chanayethazan', 'name_mm' => 'ချမ်းရည်သာဇံ', 'id' => '323'],
            ['city_id' => '8', 'name' => 'Chanmyathazi', 'name_mm' => 'ချမ်းမြသာဇီ', 'id' => '324'],
            ['city_id' => '8', 'name' => 'Kyaukpadaung', 'name_mm' => 'ကျောက်ပဒေါင်', 'id' => '325'],
            ['city_id' => '8', 'name' => 'Kyaukse', 'name_mm' => 'ကျောက်ဆည်', 'id' => '326'],
            ['city_id' => '8', 'name' => 'Lewe', 'name_mm' => 'လယ်ဝေး', 'id' => '327'],
            ['city_id' => '8', 'name' => 'Madaya', 'name_mm' => 'မတ္တရာ', 'id' => '328'],
            ['city_id' => '8', 'name' => 'Mahaaungmyay', 'name_mm' => 'မဟာအောင်မြေ', 'id' => '329'],
            ['city_id' => '8', 'name' => 'Mahlaing', 'name_mm' => 'မလှိုင်', 'id' => '330'],
            ['city_id' => '8', 'name' => 'Meiktila', 'name_mm' => 'မိတ္ထီလာ', 'id' => '331'],
            ['city_id' => '8', 'name' => 'Mogoke', 'name_mm' => 'မိုးကုတ်', 'id' => '332'],
            ['city_id' => '8', 'name' => 'Myingyan', 'name_mm' => 'မြင်းခြံ', 'id' => '333'],
            ['city_id' => '8', 'name' => 'Myittha', 'name_mm' => 'မြစ်သား', 'id' => '334'],
            ['city_id' => '8', 'name' => 'Natogyi', 'name_mm' => 'နွားထိုးကြီး', 'id' => '335'],
            ['city_id' => '8', 'name' => 'Ngazun', 'name_mm' => 'ငါန်းဇွန်', 'id' => '336'],
            ['city_id' => '8', 'name' => 'Nyaung-U', 'name_mm' => 'ညောင်ဦး', 'id' => '337'],
            ['city_id' => '8', 'name' => 'Patheingyi', 'name_mm' => 'ပုသိမ်ကြီး', 'id' => '338'],
            ['city_id' => '8', 'name' => 'Pyawbwe', 'name_mm' => 'ပျော်ဘွယ်', 'id' => '339'],
            ['city_id' => '8', 'name' => 'Pyigyitagon', 'name_mm' => 'ပြစ်ကြီးတံ', 'id' => '340'],
            ['city_id' => '8', 'name' => 'Pyinmana', 'name_mm' => 'ပြင်မနား', 'id' => '341'],
            ['city_id' => '8', 'name' => 'Pyinoolwin', 'name_mm' => 'ပြင်ဦးလွင်', 'id' => '342'],
            ['city_id' => '8', 'name' => 'Singu', 'name_mm' => 'စဉ်ကူ', 'id' => '343'],
            ['city_id' => '8', 'name' => 'Sintgaing', 'name_mm' => 'စဉ့်ကိုင်', 'id' => '344'],
            ['city_id' => '8', 'name' => 'Sintgaing', 'name_mm' => 'စဉ့်ကိုင်', 'id' => '345'],
            ['city_id' => '8', 'name' => 'Tada-U', 'name_mm' => 'တံတားဦး', 'id' => '346'],
            ['city_id' => '8', 'name' => 'Tatkon', 'name_mm' => 'တပ်ကုန်း', 'id' => '347'],
            ['city_id' => '8', 'name' => 'Taungtha', 'name_mm' => 'တောင်သာ', 'id' => '348'],
            ['city_id' => '8', 'name' => 'Thabeikkyin', 'name_mm' => 'သပိတ်ကျင်း', 'id' => '349'],
            ['city_id' => '8', 'name' => 'Thazi', 'name_mm' => 'သာစည်', 'id' => '350'],
            ['city_id' => '8', 'name' => 'Wundwin', 'name_mm' => 'ဝမ်းတွင်း', 'id' => '351'],
            ['city_id' => '8', 'name' => 'Yamethin', 'name_mm' => 'ရမည်းသင်း', 'id' => '352'],
            ['city_id' => '15', 'name' => 'Pyinmana', 'name_mm' => 'ပြင်မနား', 'id' => '353'],
            ['city_id' => '15', 'name' => 'Tatkon', 'name_mm' => 'တပ်ကုန်း', 'id' => '354'],
            ['city_id' => '15', 'name' => 'Lewe', 'name_mm' => 'လယ်ဝေး', 'id' => '355'],
            ['city_id' => '15', 'name' => 'Ottarathiri', 'name_mm' => 'ဥတ္တရသီရိ', 'id' => '356'],
            ['city_id' => '15', 'name' => 'Dekkhinathiri', 'name_mm' => 'တိုင်းဒက္ခိဏသီရိ', 'id' => '357'],
            ['city_id' => '15', 'name' => 'Pobbathiri', 'name_mm' => 'ပုဗ္ဗသီရိ', 'id' => '358'],
            ['city_id' => '15', 'name' => 'Zabuthiri', 'name_mm' => 'ဇဘူသီရိ', 'id' => '359'],
            ['city_id' => '15', 'name' => 'Zeyathiri', 'name_mm' => 'ဇေယျသီရိ', 'id' => '360'],
            ['city_id' => '8', 'name' => 'Bagan', 'name_mm' => 'ပုဂံ', 'id' => '361'],
            ['city_id' => '8', 'name' => 'Old Bagan', 'name_mm' => 'ပုဂံဦး', 'id' => '362'],
            ['city_id' => '8', 'name' => 'New Bagan', 'name_mm' => 'ပုဂံမြို့သစ်', 'id' => '363'],
        );

        foreach ($objs as $d) {
            Township::create($d);
        }
    }
}
